---
boisly:
  is:
    cool: true
    convenient: true
    opinionated: false
  createdBy: piboistudiozzzzzzzzzzzz
  utility: 10
  niftToGriftRatio: 0.9
  binaryBlurb: Ym9pc2x5Li4uIGl0IGFpbnQgeW8gZ3JhbmQgZGFkZHkncyBidXNpbmVzcyBjb29w
